version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
    ports:
      - "5678:5678"
    depends_on:
      - pgbouncer

  pgbouncer:
    build: .
    restart: always
    ports:
      - "6432:6432"
